name: kanban_task_manager
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  bloc_test: ^9.1.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pngs/app-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/pngs/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/pngs/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/font/PlusJakartaSans-Bold.ttf
        - asset: assets/font/PlusJakartaSans-BoldItalic.ttf
        - asset: assets/font/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/font/PlusJakartaSans-ExtraBoldItalic.ttf
        - asset: assets/font/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/font/PlusJakartaSans-ExtraLightItalic.ttf
        - asset: assets/font/PlusJakartaSans-Italic.ttf
        - asset: assets/font/PlusJakartaSans-Light.ttf
        - asset: assets/font/PlusJakartaSans-LightItalic.ttf
        - asset: assets/font/PlusJakartaSans-Medium.ttf
        - asset: assets/font/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/font/PlusJakartaSans-Regular.ttf
        - asset: assets/font/PlusJakartaSans-SemiBold.ttf
        - asset: assets/font/PlusJakartaSans-SemiBoldItalic.ttf
