name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if tag exists
        if: github.ref_type != 'tag'
        run: |
          echo "No tag found. Exiting..."
          exit 1

      - name: Debug environment variables
        run: |
          if [ -n "${KEYSTORE_PASSWORD}" ]; then
            echo "KEYSTORE_PASSWORD is set: yes"
          else
            echo "KEYSTORE_PASSWORD is not set."
          fi
          if [ -n "${KEY_ALIAS}" ]; then
            echo "KEY_ALIAS is set: yes"
          else
            echo "KEY_ALIAS is not set."
          fi
          if [ -n "${KEY_PASSWORD}" ]; then
            echo "KEY_PASSWORD is set: yes"
          else
            echo "KEY_PASSWORD is not set."
          fi
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      
      - name: Set up Inno Setup
        run: |
          choco install innosetup -y

      - name: Clear Gradle cache
        run: rm -rf ~/.gradle/caches/

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Clear Flutter cache
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Build appBundle
        run: flutter build appbundle

      - name: Build windows
        run: flutter build windows

      - name: Run Inno Setup to create Windows installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" win_installers/desktop_inno_script.iss

      - name: Upload release APK and AppBundle
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            win_installers/Kanban_setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
