name: Build and Release APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      # Step 3: Clear Flutter cache
      - name: Clear Flutter cache
        run: flutter clean

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Decode keystore
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release-key.jks

      # Step 6: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 7: Upload release APK to GitHub
      - name: Upload release APK to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
